### ISSUE TITLE
macOS BigSur (11.6.1) not supported for install.sh

### ISSUE THREAD

**Issue by gabizou** [mbarley333/linkchecker#6]
Discovered the install.sh script doesn't support `Darwin x86_64` as a platform, specifically I get this output for `uname -s` `x86_64`

I assume it's the same as `amd64`, so maybe just need to add that release to the install.sh if statements?

**Comment by mbarley333** [comment]
Thanks @gabizou !  I'll take a look at it

**Comment by mbarley333** [comment]
I tested it out the fix on a darwin x86_64 machine and it is working now.  Thank you!
